### ISSUE TITLE
Fix layout of wish list items

### ISSUE THREAD

**Issue by joeyblair26** [t-haskell/Team7_Solemates#28]
Description
Fix the layout of the shoes in the wish list, such as centering the picture, making the text align, etc.
Have a fixed wishlist on the side that allows you to drag items into it. 

Timing Information 3/10
Shouldn't be too hard, just using css to move items around.

Acceptance Criteria
- Wishlist is clean and still functional

**Comment by TabethaChubb** [comment]
completed - can be aesthetically edited later
