### ISSUE TITLE
User Declaration

### ISSUE THREAD

**Issue by t-haskell** [t-haskell/Team7_Solemates#4]
**Description**
Create a drop-down menu to choose what type of user you are, customer, employee, or owner. This selection changes what you are able to do on the website.

**Timing Information** 6/10
Create a drop-down menu with 3 options on it. Make the options change the state of user.

**Acceptance Criteria**
- Drops down menu
- Shows all three user options

**Comment by joeyblair26** [comment]
> Must be an initial screen with button options for the user to select their role. From that point on, the user is displayed the corresponding list of shoes based on their choice. User keeps that role for the rest of the session.
